required-players: 2

#In seconds
seeker-wait-time: 5
countdown-time: 15
match-time: 150

spawn:
  world: 'world'
  x: 34.5
  y: 36.0
  z: -50.5
  yaw: -180.0
  pitch: 0.0

arena:
  name: 'arena0Biomes'
  hider-spawns:
    0:
      world: 'world'
      x: -9
      y: 6.0
      z: -32.0
      yaw: -90.0
      pitch: 0.0
    1:
      world: 'world'
      x: -9
      y: 6.0
      z: -46.0
      yaw: -90.0
      pitch: 0.0
    2:
      world: 'world'
      x: 5
      y: 6.0
      z: -32.0
      yaw: -90.0
      pitch: 0.0
    3:
      world: 'world'
      x: 5
      y: 6.0
      z: -46.0
      yaw: -90.0
      pitch: 0.0
    4:
      world: 'world'
      x: 5.0
      y: 6.0
      z: -60.0
      yaw: -90.0
      pitch: 0.0
    5:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -69.0
      yaw: 0.0
      pitch: 0.0
    6:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -60.0
      yaw: 0.0
      pitch: 0.0
    7:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -45.0
      yaw: -90.0
      pitch: 0.0
    8:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -32.0
      yaw: -90.0
      pitch: 0.0
    9:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -25.0
      yaw: -180.0
      pitch: 0.0
    10:
      world: 'world'
      x: 19.0
      y: 6.0
      z: -18.0
      yaw: 180.0
      pitch: 0.0
    11:
      world: 'world'
      x: 26.0
      y: 6.0
      z: -25.0
      yaw: -135.0
      pitch: 0.0
    12:
      world: 'world'
      x: 26.0
      y: 6.0
      z: -32.0
      yaw: -90.0
      pitch: 0.0
    13:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -69.0
      yaw: 0.0
      pitch: 0.0
    14:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -60.0
      yaw: 0.0
      pitch: 0.0
    15:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -60.0
      yaw: 0.0
      pitch: 0.0
    16:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -32.0
      yaw: 180.0
      pitch: 0.0
    17:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -25.0
      yaw: 180.0
      pitch: 0.0
    18:
      world: 'world'
      x: 33.0
      y: 6.0
      z: -18.0
      yaw: 180.0
      pitch: 0.0
    19:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -18.0
      yaw: 180.0
      pitch: 0.0
    20:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -25.0
      yaw: 180.0
      pitch: 0.0
    21:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -32.0
      yaw: 180.0
      pitch: 0.0
    22:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -39.0
      yaw: -90.0
      pitch: 0.0
    23:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -46.0
      yaw: 90.0
      pitch: 0.0
    24:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -60.0
      yaw: 90.0
      pitch: 0.0
    25:
      world: 'world'
      x: 47.0
      y: 6.0
      z: -69.0
      yaw: 0.0
      pitch: 0.0
    26:
      world: 'world'
      x: 61.0
      y: 6.0
      z: -69.0
      yaw: 0.0
      pitch: 0.0
    27:
      world: 'world'
      x: 61.0
      y: 6.0
      z: -60.0
      yaw: 90.0
      pitch: 0.0
    28:
      world: 'world'
      x: 61.0
      y: 6.0
      z: -39.0
      yaw: 90.0
      pitch: 0.0
    29:
      world: 'world'
      x: 61.0
      y: 6.0
      z: -32.0
      yaw: 90.0
      pitch: 0.0
    30:
      world: 'world'
      x: 61.0
      y: 6.0
      z: -18.0
      yaw: 90.0
      pitch: 0.0
    31:
      world: 'world'
      x: 70.0
      y: 6.0
      z: -39.0
      yaw: 90.0
      pitch: 0.0
    32:
      world: 'world'
      x: 70.0
      y: 6.0
      z: -60.0
      yaw: 90.0
      pitch: 0.0
    33:
      world: 'world'
      x: 70.0
      y: 6.0
      z: -69.0
      yaw: 0.0
      pitch: 0.0

  seeker-spawn:
    world: 'world'
    x: 51.5
    y: 6.0
    z: -54.5
    yaw: 0.0
    pitch: 0.0